### ISSUE TITLE
Webmin missing?

### ISSUE THREAD

**Issue by codedmind** [boospy/Ubuntu-LXC-Terminalserver-Project#1]
Webmin appears to be missing
Isn't installed nor running

**Comment by boospy** [comment]
Something must have been lost in the build process. Thanks for the info. A new image will be uploaded this week.

**Comment by boospy** [comment]
Is fixe, new Image uploaded, but apparently SF is having a problem right now to download files. In the meantime, feel free to download it directly from my gitlab. Should also be available on SF again in a few hours.

https://git.osit.cc/public-projects/ubuntu-lxc-terminalserver-project/-/blob/main/UBD-22.04-Ubuntu-LXC-Terminalserver-Project_22.04-3-1_amd64.tar.gz

or you can also install webmin manualy on your system: 

```
curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```
