### ISSUE TITLE
UBD-20.04-businessdesktop_20.04-6 - ERROR

### ISSUE THREAD

**Issue by retroban** [boospy/Ubuntu-LXC-Terminalserver-Project#2]
UBD-20.04-businessdesktop_20.04-6_amd64.tar --- ERROR----
Logical volume "vm-101-disk-0" created.
Creating filesystem with 5242880 4k blocks and 1310720 inodes
Filesystem UUID: b24c41f4-b648-4bb2-a175-f560be8658b3
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
extracting archive '/var/lib/vz/template/cache/UBD-20.04-businessdesktop_20.04-6_amd64.tar.gz'
tar: ./var/spool/postfix/dev/random: Cannot mknod: Operation not permitted
tar: ./var/spool/postfix/dev/urandom: Cannot mknod: Operation not permitted
Total bytes read: 6309120000 (5.9GiB, 136MiB/s)
tar: Exiting with failure status due to previous errors
  Logical volume "vm-101-disk-0" successfully removed.
TASK ERROR: unable to create CT 101 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - -z --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/101/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2

**Comment by boospy** [comment]
Have you used unprivileged container: "no" ?

**Comment by retroban** [comment]
We managed to create a container using the preferred container mode. The solution to fix the template is here - https://forum.proxmox.com/threads/unprivileged-containers.26148/

**Comment by boospy** [comment]
Unprivileged container is not supported for desktop systems. So please use unprivileged container: "no"

**Comment by retroban** [comment]
I plan to make a backup copy and restore as an “Unprivileged container” using the following solution - https://forum.proxmox.com/threads/unprivileged-containers.26148/page-2#post-207631, since using privileged container mode is bad solution for the business for which this template was created.

**Comment by retroban** [comment]
In addition, version 22 works exactly as an “Unprivileged container”, I won’t use version 20, I just want to check if it has tinyotp

**Comment by boospy** [comment]
https://github.com/boospy/Ubuntu-LXC-Terminalserver-Project/issues/3#issuecomment-1971028403

**Comment by boospy** [comment]
> I plan to make a backup copy and restore as an “Unprivileged container” 

Not all of programs working fine with it.

**Comment by retroban** [comment]
The method of changing the container configuration by adding mount lines for the host system directories (/dev/random and /dev/urandom), as well as backup/restore, works. I would like to receive information about which programs will not work, what you wrote above.

**Comment by boospy** [comment]
I can't remember exactly which one, as it was years ago, but Postfix, for example, was one of them. It no longer worked properly, for example. Also with mounts in the Active Directory  i had a lot of troubles.

**Comment by boospy** [comment]
Updated to new Version. Added Tinyotp and changed to english as default language.
