### ISSUE TITLE
UBD-22.04-Ubuntu-LXC-Terminalserver-Project_22.04-3-1 -- Not tinyOTP (2Factor)

### ISSUE THREAD

**Issue by retroban** [boospy/Ubuntu-LXC-Terminalserver-Project#3]
The project 22.04 does not have the tinyOTP (2Factor) software product, I can’t check version 20.04, there was an installation error. (made a separate topic). Unfortunately, I still don’t understand how to add this from the source code from https://github.com/theinvisible/tinyotp
I would be grateful for a description of the process. It’s also interesting to read how you put this image together and repeat it yourself, with some changes.

**Comment by boospy** [comment]
Yes, you can use easy apt to install the program: 
`apt install tinyotp`

**Comment by retroban** [comment]
In general, if it weren’t for the outdated version and the problem with privileged containers that are not accessible for business, I liked the project based on version 20.04 more:
1. English as a basic language and no others.
2. There is Google Chrome and TinyOTP.
3. The list of installed applications is more optimal.
But it also has its own errors, for example a problem with the network manager, which shows no connection in the tray, although there is a connection..
I haven’t figured out the rest yet, but still the idea is ideal, the implementation is still 4 out of 5. First of all, it seems to me that the description needs to be corrected, because it describes something between versions 20.04 and 22.04.

**Comment by retroban** [comment]
Thank you for your work, in any case, I have never seen a better project than yours on the Internet. I’ll at least try using a template and Ansible until I figure out LXC containerization in ProxMox and how to create templates myself. Then I’ll make my own with a different distribution and a different set of software.

**Comment by boospy** [comment]
Updated to new Version. Added Tinyotp and changed to english as default language.
